#!/usr/bin/env ruby

input_file = ARGV[0]
output_file = ARGV[1]

def pather(input, output)
  File.open(output, 'w') do |f|
    File.readlines(input).each do |row|
      f << row
    end
  end
end

pather(input_file, output_file)